// <auto-generated />
using System;
using HouseholdManager.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HouseholdManager.Migrations
{
    [DbContext(typeof(HouseholdManagerDbContext))]
    partial class HouseholdManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HouseholdManager.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a1addd14-6340-4840-95c2-db12554843e5",
                            AccessFailedCount = 0,
                            Age = 30,
                            ConcurrencyStamp = "2ac415df-4b9a-4c52-87df-4a817cd30873",
                            Email = "defaultAdmin1@yahoo.com",
                            EmailConfirmed = false,
                            FirstName = "DefaultAdmin1",
                            LastName = "DefaultAdmin1",
                            LockoutEnabled = true,
                            NormalizedEmail = "DEFAULTADMIN1@YAHOO.COM",
                            NormalizedUserName = "DEFAULTADMIN@YAHOO.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEMx8WasbAraoT19NKPQ/b7bdY6kqo5W7pHrv0R8iyri+Y8WCnzeqnWosG+dMIBT8bQ==",
                            PhoneNumber = "111-222-3333",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a6949b86-2d8b-493a-b252-d753656fbfdc",
                            TwoFactorEnabled = false,
                            UserName = "defaultAdmin1@yahoo.com"
                        },
                        new
                        {
                            Id = "u1ua87c6-b718-4f48-90a2-458e0a2443e6",
                            AccessFailedCount = 0,
                            Age = 15,
                            ConcurrencyStamp = "c61e98ad-470b-4602-8c91-bc834602ccfe",
                            Email = "defaultUser@yahoo.com",
                            EmailConfirmed = false,
                            FirstName = "DefaultUser",
                            LastName = "DefaultUser",
                            LockoutEnabled = true,
                            NormalizedEmail = "DEFAULTUSER@YAHOO.COM",
                            NormalizedUserName = "DEFAULTUSER@YAHOO.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEPWRBw0s4mrLCudIIuhvtQG9tI0Y6X1Hx7thX1+i6CFvNolxOlQkoebVNGPppG9seQ==",
                            PhoneNumber = "111-222-3333",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9ce7dbd8-7802-430d-be6f-ae30354c2c3d",
                            TwoFactorEnabled = false,
                            UserName = "defaultUser@yahoo.com"
                        });
                });

            modelBuilder.Entity("HouseholdManager.Models.Contributor", b =>
                {
                    b.Property<int>("ContributorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContributorId"), 1L, 1);

                    b.Property<string>("ContributorIcon")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContributorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContributorId");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("UserId");

                    b.ToTable("Contributors");

                    b.HasData(
                        new
                        {
                            ContributorId = 1,
                            ContributorIcon = "👩‍🔧",
                            ContributorType = "Admin",
                            HouseholdId = 1,
                            UserName = "defaultAdmin@yahoo.com"
                        },
                        new
                        {
                            ContributorId = 2,
                            ContributorIcon = "👩‍💼",
                            ContributorType = "Contributor",
                            HouseholdId = 1,
                            UserName = "defaultUser@yahoo.com"
                        });
                });

            modelBuilder.Entity("HouseholdManager.Models.Household", b =>
                {
                    b.Property<int>("HouseholdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HouseholdId"), 1L, 1);

                    b.Property<string>("HouseholdIcon")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HouseholdName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("HouseholdId");

                    b.ToTable("Households");

                    b.HasData(
                        new
                        {
                            HouseholdId = 1,
                            HouseholdIcon = "🏠",
                            HouseholdName = "DefaultHousehold"
                        });
                });

            modelBuilder.Entity("HouseholdManager.Models.Mission", b =>
                {
                    b.Property<int>("MissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MissionId"), 1L, 1);

                    b.Property<int>("ContributorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MissionIcon")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MissionInstructions")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MissionPoints")
                        .HasColumnType("int");

                    b.Property<string>("MissionStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("MissionId");

                    b.HasIndex("ContributorId");

                    b.HasIndex("RoomId");

                    b.ToTable("Missions");

                    b.HasData(
                        new
                        {
                            MissionId = 1,
                            ContributorId = 2,
                            MissionDate = new DateTime(2023, 1, 25, 12, 17, 14, 221, DateTimeKind.Local).AddTicks(7272),
                            MissionIcon = "🍴",
                            MissionName = "Wash dishes",
                            MissionPoints = 2,
                            MissionStatus = "ToDo",
                            RoomId = 1
                        },
                        new
                        {
                            MissionId = 2,
                            ContributorId = 1,
                            MissionDate = new DateTime(2023, 1, 25, 12, 17, 14, 221, DateTimeKind.Local).AddTicks(7288),
                            MissionIcon = "🛏",
                            MissionName = "Make bed",
                            MissionPoints = 1,
                            MissionStatus = "ToDo",
                            RoomId = 5
                        },
                        new
                        {
                            MissionId = 3,
                            ContributorId = 2,
                            MissionDate = new DateTime(2023, 1, 25, 12, 17, 14, 221, DateTimeKind.Local).AddTicks(7298),
                            MissionIcon = "🛏",
                            MissionName = "Make bed",
                            MissionPoints = 1,
                            MissionStatus = "ToDo",
                            RoomId = 3
                        },
                        new
                        {
                            MissionId = 4,
                            ContributorId = 1,
                            MissionDate = new DateTime(2023, 1, 25, 12, 17, 14, 221, DateTimeKind.Local).AddTicks(7328),
                            MissionIcon = "✂",
                            MissionName = "Mow lawn",
                            MissionPoints = 5,
                            MissionStatus = "ToDo",
                            RoomId = 9
                        },
                        new
                        {
                            MissionId = 5,
                            ContributorId = 1,
                            MissionDate = new DateTime(2023, 1, 25, 12, 17, 14, 221, DateTimeKind.Local).AddTicks(7338),
                            MissionIcon = "🍗",
                            MissionName = "Make dinner",
                            MissionPoints = 4,
                            MissionStatus = "ToDo",
                            RoomId = 1
                        });
                });

            modelBuilder.Entity("HouseholdManager.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"), 1L, 1);

                    b.Property<string>("RoomIcon")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            RoomIcon = "🥄",
                            RoomName = "Kitchen"
                        },
                        new
                        {
                            RoomId = 2,
                            RoomIcon = "🧻",
                            RoomName = "Bathroom"
                        },
                        new
                        {
                            RoomId = 3,
                            RoomIcon = "🛏",
                            RoomName = "Master Bedroom"
                        },
                        new
                        {
                            RoomId = 4,
                            RoomIcon = "🛋",
                            RoomName = "Living Room"
                        },
                        new
                        {
                            RoomId = 5,
                            RoomIcon = "🛏",
                            RoomName = "Bedroom"
                        },
                        new
                        {
                            RoomId = 6,
                            RoomIcon = "🛏",
                            RoomName = "Guest Bedroom"
                        },
                        new
                        {
                            RoomId = 7,
                            RoomIcon = "🧻",
                            RoomName = "Master Bathroom"
                        },
                        new
                        {
                            RoomId = 8,
                            RoomIcon = "🍽",
                            RoomName = "Dining Room"
                        },
                        new
                        {
                            RoomId = 9,
                            RoomIcon = "🌳",
                            RoomName = "Yard"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "fab4fac1-c546-41de-aebc-a14da6895711",
                            ConcurrencyStamp = "1",
                            Name = "Administrator",
                            NormalizedName = "Administrator"
                        },
                        new
                        {
                            Id = "c7b013f0-5201-4317-abd8-c211f91b7330",
                            ConcurrencyStamp = "2",
                            Name = "User",
                            NormalizedName = "User"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "a1addd14-6340-4840-95c2-db12554843e5",
                            RoleId = "fab4fac1-c546-41de-aebc-a14da6895711"
                        },
                        new
                        {
                            UserId = "a1addd14-6340-4840-95c2-db12554843e5",
                            RoleId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        },
                        new
                        {
                            UserId = "u1ua87c6-b718-4f48-90a2-458e0a2443e6",
                            RoleId = "c7b013f0-5201-4317-abd8-c211f91b7330"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HouseholdManager.Models.Contributor", b =>
                {
                    b.HasOne("HouseholdManager.Models.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseholdManager.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Household");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HouseholdManager.Models.Mission", b =>
                {
                    b.HasOne("HouseholdManager.Models.Contributor", "Contributor")
                        .WithMany()
                        .HasForeignKey("ContributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseholdManager.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contributor");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HouseholdManager.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HouseholdManager.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseholdManager.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HouseholdManager.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
